#!/usr/bin/env bash
# Configures a server listening on port 80 of all servers with IPv4 IPs

# Remove Nginx default config file
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default Nginx config for IPv4
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart
