#!/usr/bin/env bash
# configu a serv to liste port 80 of all servers actve IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
